In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("marksheet.csv")

In [4]:
df

      id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81       62     49
1      2    Lemmie    Male   15       B       29       41       17     40
2      3     Danya  Female   14       C       12       87       16     96
3      4     Denna  Female   14       B       15       53       82     33
4      5   Jocelin    Male   14       A       43        6        3     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15       25     10
246  247       Rog  Female   13       B        1        4       68     65
247  248      Kaia    Male   15       B       93       48       82     44
248  249      Anni  Female   14       B       35       73       66     59
249  250  Fernande    Male   15       B       50        8       80     78

[250 rows x 9 columns]

1. read students marks from csv 
2. Read student marks from a CSV
3. Calculate total, percentage, grade
4. Find topper
5. Subject-wise average
6. Save processed report

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       250 non-null    int64
 1   Name     250 non-null    object
 2   Gender   250 non-null    object
 3   Age      250 non-null    int64
 4   Section  250 non-null    object
 5   Science  250 non-null    int64
 6   English  250 non-null    int64
 7   History  250 non-null    int64
 8   Maths    250 non-null    int64
dtypes: int64(6), object(3)
memory usage: 17.7+ KB

In [6]:
df.describe()

               id         Age     Science     English     History       Maths
count  250.000000  250.000000  250.000000  250.000000  250.000000  250.000000
mean   125.500000   14.020000   51.440000   47.980000   52.272000   53.016000
std     72.312977    0.823598   29.314497   29.949013   26.868526   27.386416
min      1.000000   13.000000    1.000000    1.000000    1.000000    1.000000
25%     63.250000   13.000000   25.250000   20.250000   31.000000   30.000000
50%    125.500000   14.000000   53.000000   47.500000   53.000000   52.500000
75%    187.750000   15.000000   78.000000   74.000000   76.000000   76.000000
max    250.000000   15.000000  100.000000  100.000000  100.000000  100.000000

In [7]:
df['Total marks'] = df['Science'] + df['History'] + df['English'] + df["Maths"]

In [8]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total marks
0,1,Bronnie,Female,13,C,21,81,62,49,213
1,2,Lemmie,Male,15,B,29,41,17,40,127
2,3,Danya,Female,14,C,12,87,16,96,211
3,4,Denna,Female,14,B,15,53,82,33,183
4,5,Jocelin,Male,14,A,43,6,3,21,73
...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78
246,247,Rog,Female,13,B,1,4,68,65,138
247,248,Kaia,Male,15,B,93,48,82,44,267
248,249,Anni,Female,14,B,35,73,66,59,233
249,250,Fernande,Male,15,B,50,8,80,78,216

In [9]:
df['Percentage'] = df["Total marks"]/ 4

In [10]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total marks,Percentage
0,1,Bronnie,Female,13,C,21,81,62,49,213,53.25
1,2,Lemmie,Male,15,B,29,41,17,40,127,31.75
2,3,Danya,Female,14,C,12,87,16,96,211,52.75
3,4,Denna,Female,14,B,15,53,82,33,183,45.75
4,5,Jocelin,Male,14,A,43,6,3,21,73,18.25
...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78,19.50
246,247,Rog,Female,13,B,1,4,68,65,138,34.50
247,248,Kaia,Male,15,B,93,48,82,44,267,66.75
248,249,Anni,Female,14,B,35,73,66,59,233,58.25
249,250,Fernande,Male,15,B,50,8,80,78,216,54.00

In [18]:
def grade(per):
    if per >= 90:
        return "A+"
    elif per >= 80:
        return "A"
    elif per >= 70:
        return "B"
    elif per >= 60:
        return "C"
    elif per >= 50:
        return "D"
    elif per >= 40:
        return "E"
    else:
        return "F"

df["Grade"] = df["Percentage"].apply(grade)

In [19]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total marks,Percentage,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,53.25,D
1,2,Lemmie,Male,15,B,29,41,17,40,127,31.75,F
2,3,Danya,Female,14,C,12,87,16,96,211,52.75,D
3,4,Denna,Female,14,B,15,53,82,33,183,45.75,E
4,5,Jocelin,Male,14,A,43,6,3,21,73,18.25,F
...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78,19.50,F
246,247,Rog,Female,13,B,1,4,68,65,138,34.50,F
247,248,Kaia,Male,15,B,93,48,82,44,267,66.75,C
248,249,Anni,Female,14,B,35,73,66,59,233,58.25,D
249,250,Fernande,Male,15,B,50,8,80,78,216,54.00,D

In [26]:
df[df["Total marks"]==df["Total marks"].max()]

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total marks,Percentage,Grade
10,11,Dunn,Male,15,C,100,93,87,81,361,90.25,A+

In [34]:
df.sort_values(by= "Total marks", ascending= False,inplace= True)

In [37]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total marks,Percentage,Grade
10,11,Dunn,Male,15,C,100,93,87,81,361,90.25,A+
120,121,Patrizia,Male,13,A,79,88,96,93,356,89.00,A
68,69,Nil,Female,15,A,84,97,70,96,347,86.75,A
91,92,Daffi,Female,15,A,79,82,99,81,341,85.25,A
200,201,Ruddie,Female,15,B,84,97,88,64,333,83.25,A
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,Jocelin,Male,14,A,43,6,3,21,73,18.25,F
137,138,Berget,Male,13,C,10,29,21,13,73,18.25,F
225,226,Blake,Female,15,B,16,4,49,1,70,17.50,F
19,20,Ashlan,Male,13,B,41,6,17,3,67,16.75,F
228,229,Ginnifer,Female,14,C,4,15,6,32,57,14.25,F

In [38]:
df1 = df["English"].mean()
df1

np.float64(47.98)