In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\sachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\sachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\sachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\sachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

CREATING A DATA FRAME

In [3]:
import numpy as np
import pandas as pd

In [4]:
data ={
    'name':['jhon','anna','peter','linda'],
    'age': [28,30,32,23],
    'city':['new york','paris','berlin','london'],
    'salary':[65000,70000,62000,85000]
}
pd.DataFrame(data)

    name  age      city  salary
0   jhon   28  new york   65000
1   anna   30     paris   70000
2  peter   32    berlin   62000
3  linda   23    london   85000

In [5]:
data_list=[
    ['jhon',28,'newyork',65000],
    ['anna',30,'paris',70000],
    ['peter',32,'berlin',62000],
    ['linda',23,'london',85000]
]

In [6]:
df2=pd.DataFrame(data_list)
columns = ["name","age","city","salary"]
df2 =pd.DataFrame(data_list,columns = columns)

In [7]:
df2

    name  age     city  salary
0   jhon   28  newyork   65000
1   anna   30    paris   70000
2  peter   32   berlin   62000
3  linda   23   london   85000

SELECTING AND INDEXING OF COLUMNS

In [8]:
df2['name']

0     jhon
1     anna
2    peter
3    linda
Name: name, dtype: object

In [9]:
df2[['name','city']]

    name     city
0   jhon  newyork
1   anna    paris
2  peter   berlin
3  linda   london

CREATING A NEW COLUMN

In [10]:
df2["desination"] = ["doctor","Engineer","doctor","Engineer"]
df2

    name  age     city  salary desination
0   jhon   28  newyork   65000     doctor
1   anna   30    paris   70000   Engineer
2  peter   32   berlin   62000     doctor
3  linda   23   london   85000   Engineer

REMOVE COLUMN

In [11]:
df2.drop('desination',axis = 1)

    name  age     city  salary
0   jhon   28  newyork   65000
1   anna   30    paris   70000
2  peter   32   berlin   62000
3  linda   23   london   85000

In [12]:
df2.drop(0,axis = 0)

    name  age    city  salary desination
1   anna   30   paris   70000   Engineer
2  peter   32  berlin   62000     doctor
3  linda   23  london   85000   Engineer

selecting rows

In [13]:
df2.loc[[0,1]]

   name  age     city  salary desination
0  jhon   28  newyork   65000     doctor
1  anna   30    paris   70000   Engineer

selecting subset of rows and columns

In [14]:
df2

    name  age     city  salary desination
0   jhon   28  newyork   65000     doctor
1   anna   30    paris   70000   Engineer
2  peter   32   berlin   62000     doctor
3  linda   23   london   85000   Engineer

In [15]:
df2.loc[[0,1]][["city","salary"]]

      city  salary
0  newyork   65000
1    paris   70000

In [16]:
df2.loc[[2,3]][["name","age"]]

    name  age
2  peter   32
3  linda   23

condition selection

In [17]:
df2

    name  age     city  salary desination
0   jhon   28  newyork   65000     doctor
1   anna   30    paris   70000   Engineer
2  peter   32   berlin   62000     doctor
3  linda   23   london   85000   Engineer

In [18]:
#i only want to see those people whose age is above 30

In [19]:
df2[df2["age"]>30]

    name  age    city  salary desination
2  peter   32  berlin   62000     doctor

In [20]:
# i only want people whose age is above 30 and their city must be berlin

In [26]:
df2[(df2["age"]>30) & (df2["city"]=="berlin")]

    name  age    city  salary desination
2  peter   32  berlin   62000     doctor