In [1]:
import numpy as np
import pandas as pd

pivot table

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    327     32   John  January      Q1
1  2023-01-02       B   West    279     25   Mary  January      Q1
2  2023-01-03       C  North    274     31    Bob  January      Q1
3  2023-01-04       D  South    423     38  Alice  January      Q1
4  2023-01-05       A   East    477     38   John  January      Q1
5  2023-01-06       B   West    241     88   Mary  January      Q1
6  2023-01-07       C  North    634     23    Bob  January      Q1
7  2023-01-08       D  South    465     25  Alice  January      Q1
8  2023-01-09       A   East    337     80   John  January      Q1
9  2023-01-10       B   West    940     79   Mary  January      Q1
10 2023-01-11       C  North    244     88    Bob  January      Q1
11 2023-01-12       D  South    707     54  Alice  January      Q1
12 2023-01-13       A   East    563     51   John  January      Q1
13 2023-01-14       B   West    997     55   Mary  January      Q1
14 2023-01-15       C  North    742     54    Bob  January      Q1
15 2023-01-16       D  South    181     62  Alice  January      Q1
16 2023-01-17       A   East    692     89   John  January      Q1
17 2023-01-18       B   West    964     18   Mary  January      Q1
18 2023-01-19       C  North    975     16    Bob  January      Q1
19 2023-01-20       D  South    936     10  Alice  January      Q1

In [3]:
pd.pivot_table(df,values="Sales",index="Region",columns ="Product",aggfunc='median')

Product      A      B      C      D
Region
East     477.0    NaN    NaN    NaN
North      NaN    NaN  634.0    NaN
South      NaN    NaN    NaN  465.0
West       NaN  940.0    NaN    NaN

In [4]:
pivot2= pd.pivot_table(df,values=['Units','Sales'], index = 'Region',columns ='Product')

In [5]:
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     479.2    NaN    NaN    NaN  58.0   NaN   NaN   NaN
North      NaN    NaN  573.8    NaN   NaN   NaN  42.4   NaN
South      NaN    NaN    NaN  542.4   NaN   NaN   NaN  37.8
West       NaN  684.2    NaN    NaN   NaN  53.0   NaN   NaN

CROSS TAB

In [6]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [7]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    327     32   John  January      Q1
1  2023-01-02       B   West    279     25   Mary  January      Q1
2  2023-01-03       C  North    274     31    Bob  January      Q1
3  2023-01-04       D  South    423     38  Alice  January      Q1
4  2023-01-05       A   East    477     38   John  January      Q1
5  2023-01-06       B   West    241     88   Mary  January      Q1
6  2023-01-07       C  North    634     23    Bob  January      Q1
7  2023-01-08       D  South    465     25  Alice  January      Q1
8  2023-01-09       A   East    337     80   John  January      Q1
9  2023-01-10       B   West    940     79   Mary  January      Q1
10 2023-01-11       C  North    244     88    Bob  January      Q1
11 2023-01-12       D  South    707     54  Alice  January      Q1
12 2023-01-13       A   East    563     51   John  January      Q1
13 2023-01-14       B   West    997     55   Mary  January      Q1
14 2023-01-15       C  North    742     54    Bob  January      Q1
15 2023-01-16       D  South    181     62  Alice  January      Q1
16 2023-01-17       A   East    692     89   John  January      Q1
17 2023-01-18       B   West    964     18   Mary  January      Q1
18 2023-01-19       C  North    975     16    Bob  January      Q1
19 2023-01-20       D  South    936     10  Alice  January      Q1

In [8]:
pivot3= pd.pivot_table(df,values='Units',index='Product',columns='Rep')

In [9]:
pivot3

Rep      Alice   Bob  John  Mary
Product
A          NaN   NaN  58.0   NaN
B          NaN   NaN   NaN  53.0
C          NaN  42.4   NaN   NaN
D         37.8   NaN   NaN   NaN